In [9]:
import numpy as np
ar1=np.arange(13)

In [10]:
ar1
len(ar1)

13

In [11]:
reshaped_array=ar1.reshape(1,13)
reshaped_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [12]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#identity-->matrix can be created using two functions
#eye()-->used to define both user defined rows and columns
#identity()-->used to define same number of rows and columns
#syntax-->np.identity(5)-->5 is 5 rows and 5 columns
#syntax-->np.eye(3,4)-->3 rows and 4 columns
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
np.identity(5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
ar2=np.arange(25)
ar2.shape

(25,)

In [19]:
#to perform multidimensional slicing
ar2=np.arange(25).reshape(5,5)

In [20]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
ar2.shape

(5, 5)

In [24]:
#ar2[rows,columns,step]
#ar2=[row_start:row_end,col_start, col_end, step]
ar2[0:3, 1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [25]:
ar2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [27]:
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [28]:
ar2[-0:-4]

array([[0, 1, 2, 3, 4]])

In [29]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ar2[::1,::3]

array([[ 0,  3],
       [ 5,  8],
       [10, 13],
       [15, 18],
       [20, 23]])

In [35]:
ar2[-2]

array([15, 16, 17, 18, 19])

In [38]:
ar2[-3]

array([10, 11, 12, 13, 14])

In [44]:
ar2[-4:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [48]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
#linspace()
np.sum(ar3)

1225

In [51]:
ar3.sum()

1225

In [52]:
np.sum(ar3,axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [54]:
np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [55]:
#mean-->average
#median-->centre value
#mode-->max no.of repeated elements
#variance-->median/total no.of ele
#std-->square root of variance

In [56]:
#linspace()
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [57]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [58]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [62]:
#linspace()
#it is used to print evenly seperated pointed
#between 2 range of values
np.linspace(1,10,4,dtype=int)
#-->linspace(start end no.of parts))

array([ 1,  4,  7, 10])

In [63]:
np.linspace(1,10,4,dtype=complex)

array([ 1.+0.j,  4.+0.j,  7.+0.j, 10.+0.j])

In [64]:
np.linspace(1,10,5,dtype=float)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [71]:
#random module
#to generate random number between the range
#np.random.randint(start,end)
#np.random.randint(start,end, no_of_values)
np.random.randint(50)

48

In [72]:
np.random.randint(20,30,3)

array([25, 26, 22])

In [73]:
#rand()-->
#to get the randomly generated values from 0 to 1 based on uniform distribution
np.random.rand(4)

array([0.85983891, 0.25039193, 0.08931442, 0.69747182])

In [74]:
np.random.rand(3,4)

array([[0.47740309, 0.2411903 , 0.28381399, 0.66473284],
       [0.08703241, 0.43564042, 0.27075484, 0.14816116],
       [0.43432504, 0.28666662, 0.50211098, 0.76757401]])

In [75]:
#to get the randomly generated values from 0 to 1 based on normalised distribution
np.random.randn(5)

array([ 0.64064251,  0.17133815,  0.6121844 , -2.43841226,  0.68740086])

In [76]:
np.random.randn(5,4)

array([[-0.93371118, -0.96308225,  0.32114363, -0.04714154],
       [-0.55544511,  1.96029749, -0.12547363, -0.20365573],
       [-0.73356996, -0.11919401,  1.21891744, -1.40419095],
       [ 1.17668621,  0.62626909, -0.27023781,  0.62945981],
       [-0.13723776,  1.30786977,  0.19939793, -1.45225185]])

In [77]:
ar3.min()

0

In [78]:
ar3.max()

49

In [79]:
#to find the index of value
l1=[56,89,90,67,45]
print(l1.index(67))

3


In [80]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [83]:
l1=[56,89,90,67,45]
np1=np.array(l1)
#argmin-->to find min value index position in array
print(np1.argmin())
#argmax-->to find max value index position in array
print(np1.argmax())

4
2


In [84]:
np1

array([56, 89, 90, 67, 45])

In [86]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [89]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.89399666, -0.85551998,  0.85090352])

In [90]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [91]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [94]:
#task 1-->write python for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1x4)+(2x5)+(3x6)=4+10+18=32
sum(np2*np3)



32

In [97]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
np.dot(np2,np3)

32

In [98]:
#task 1-->write python for the below logic
np2=np.array([1,2,3,9])
np3=np.array([4,5,6,1])
sum(np2*np3)

41

In [99]:
np.dot(np2,np3)

41

In [106]:
fname=np.array(["sid","fn1",'fn2'])
lname=np.array(['T',"ln1","ln2"])
#fname.tostring()                   

In [108]:
#task 1-->write python for the below logic
np2=np.array([1,2,3,8,3,5,9])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum((np2*np3))

57

In [109]:
np1=np.array([1,34,56,78,np.nan,np.nan])
#to print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [110]:
#to eliminate nan values
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [1]:
#pandas
import pandas as pd
#pandas is define as an open-source library that provides high-performance data manipulation in python
#data analysis requires lot of pracessing such as restructing,cleaning,mergin,manipulating etc..we prefer pandas to perform the 
#above functionalities
#coz it is fast,simple than other tasks
#pandas is built on numpy is required for operating pandas

In [2]:
# pandas series
#pandas series is a data structure with one dimensional labelled array
#it is a primary building block of dataframe,making its rows and columns

In [3]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,"b":200,"c":300}

NameError: name 'np' is not defined

In [5]:
1# syntax-->pandas.series(data=none,index=none,dtype=none,name=none,copy=true(or)false)
#ex-1:
import pandas as pd
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [6]:
type(pd.Series(my_data))

pandas.core.series.Series

In [7]:
#Series with labels
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [11]:
pd.Series(data=[print(),len,sum])

0                       None
1    <built-in function len>
2    <built-in function sum>
dtype: object

In [17]:
class profile:
    @property
    def display(self):
        print("my name is 636")
p=profile()
p.display

my name is 636


In [26]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner
@decor
def greet():
    return "good morning"
print(greet())


GOOD MORNING


In [27]:
ser1=pd.Series ([1,2,3,4,5],['UsA','india','canada','uk','egypt'])
ser1

UsA       1
india     2
canada    3
uk        4
egypt     5
dtype: int64

In [35]:
ser1['egypt']

5

In [32]:
#access values using indexing
ser1[0:3]

UsA       1
india     2
canada    3
dtype: int64

In [37]:
ser2=pd.Series([5,6,7,8,9],['usa','brazil','canada','uk','paris'])
ser1+ser2

UsA        NaN
brazil     NaN
canada    10.0
egypt      NaN
india      NaN
paris      NaN
uk        12.0
usa        NaN
dtype: float64

In [41]:
#to create a new data in series
ser2['china']="duplicate" 
ser2


usa               5
brazil            6
canada            7
uk                8
paris             9
china     duplicate
dtype: object

In [42]:
ser2.drop('usa')

brazil            6
canada            7
uk                8
paris             9
china     duplicate
dtype: object

In [45]:
#dataframe
#pd.DataFrame(datas,row_label,clo_label)
import numpy as np
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -0.804036  0.323586  0.137372  0.136816
1 -1.404307  0.444228  0.456663  1.034389
2 -0.311896 -0.798386  1.089791 -0.737400
3  0.514107  0.360526  0.243067 -1.444332
4  1.619329 -1.338142  0.411972  1.136815

In [71]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  1.011328  0.007634  0.669978  1.141765
B -0.132913  0.786991  1.276522  1.533466
C -0.064981 -0.856960 -0.176468 -0.582610
D -1.562727  1.865525  0.297551  0.092499
E  0.569203 -0.093320  0.835162  0.368811

In [8]:
#to convert dictionary to dataframe
d={'col1':[1,2],'clo2':[3,4],'col3':[5,6]}
d

{'col1': [1, 2], 'clo2': [3, 4], 'col3': [5, 6]}

In [13]:
import pandas as pd
df=pd.DataFrame(data=d)
df

col1  clo2  col3
0     1     3     5
1     2     4     6

In [14]:
df=pd.DataFrame(d,['row1','row2'])
df

col1  clo2  col3
row1     1     3     5
row2     2     4     6

In [56]:
df.T

A         B         C         D         E
W -2.138331  0.097640  0.851800  0.968391  0.275476
X  0.078682  3.130549  0.427916 -0.071110 -1.455061
Y -0.851073 -1.408053 -0.586981 -2.147184  0.606945
Z -1.557863 -0.062841 -0.411424  2.038577  0.244957

In [57]:
df.index #-->get all the row name

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [58]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [59]:
type(df)

pandas.core.frame.DataFrame

In [60]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [62]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [63]:
df.values

array([[-2.13833084,  0.07868165, -0.85107341, -1.55786336],
       [ 0.09763963,  3.13054934, -1.40805309, -0.06284097],
       [ 0.85179978,  0.42791578, -0.58698062, -0.41142391],
       [ 0.96839081, -0.07110999, -2.14718373,  2.03857676],
       [ 0.27547629, -1.45506052,  0.6069451 ,  0.24495708]])

In [64]:
df.size

20

In [65]:
df.ndim

2

In [77]:
#to access specific column in  df
df

W         X         Y         Z
A  1.011328  0.007634  0.669978  1.141765
B -0.132913  0.786991  1.276522  1.533466
C -0.064981 -0.856960 -0.176468 -0.582610
D -1.562727  1.865525  0.297551  0.092499
E  0.569203 -0.093320  0.835162  0.368811

In [79]:
df['W']

A    1.011328
B   -0.132913
C   -0.064981
D   -1.562727
E    0.569203
Name: W, dtype: float64

In [82]:
type(df['W'])

pandas.core.series.Series

In [26]:
df['W','X','Y']

KeyError: ('W', 'X', 'Y')

In [20]:
#to create new column
df['new']=df['W']+df['Y']
df

KeyError: 'W'